### ISSUE TITLE
Schema Hashes

### ISSUE THREAD

**Issue by ryanhiebert** [abe-winter/automigrate#5]
Thanks for writing this. I came across your blog post and this repo from the changelog weekly email, and I'm finding it a really intriguing approach. I'm heavily in Django land, even mixing it up with SQLAlchemy in the same project (translating the Django models to SQLAlchemy with Aldjemy), which is all kinda painful, and missing some features that I'm really wanting to put in place (null-coalescing unique contraints on my tables is one particular headache), so this approach makes me wonder if it may be a better way to handle things.

> Schema should be versioned using the same git shas as code so the logic is easy to detect if a deploy requires a migration

This philosophical requirements is what causes the issues with rebasing, even if the schema isn't changing or conflicting. I'm not sure I'm sold on it. I do see value in versioning based on a hash of the schema, and I think that's the right choice, though. So what might be the _right_ hash, that didn't mess up rebasing, etc?

I'll consider it by way of a similar problem, and let you poke holes in that problem, or the parallel I wish to draw with this project. I want to build docker images from my code. I want to build those docker images for each commit in my master branch, as well as for my pull requests, which are my unit of review and testing before shipping it to production. I'd like to be able to merge from the GitHub web interface, which should kick off automated build, test, and deployment. And, critically, I'd like it to not rebuild the docker image if it doesn't need to.

Unfortunately, _every_ GitHub option for merging will change commit sha from the one at the head of the PR branch, so using the commit hash doesn't solve the final requirement to not rebuild the image if it doesn't need to. The solution that I've come up with is to _not_ use the commit hash, but to instead use the hash of the repository tree instead. This is still calculated by Git, is easy to get to with a git command, and is based solely on the content of the repository, not the content, author, or dates on the commit, since those just don't matter to what I'm doing. The downside to that is that it's significantly more annoying to determine, from the tree hash, which commit in the repo has that tree hash. Especially since its the commit that is easily available in the GitHub UI and most git commands.

While I don't love the downsides I've just mentioned, my current thinking is that the correctness of identification is worth the trade. Applied to this project, I'd expect that it might be the hash of the schema file or files instead of the git commit hash. If that schema is in just one file, then, like my approach of using the git tree hash, you could use git to give you the blob hash of that file at the current commit. Or if its the entire contents of a folder, a tree hash of that folder at the current commit would work.

My motivation here is based on my philosophy of using Git, which is fine with rebasing. It's not for every situation, and should be done with care, but rebasing is, fundamentally, editing a line of communication with users of your code via your history. It's important to keep that looking good, IMO, when it doesn't conflict with other important concerns a person's project, like tracking deployments and keeping things safe to share, etc.

**Comment by abe-winter** [comment]
yes, this project works best on a linear history -- the intended use-case is migrations applied from master

can you tell me more about your use case? why does a migration require a docker rebuild?

**Comment by ryanhiebert** [comment]
I'm sorry if my example was confusing. I wasn't describing directly a scenario for migrations, but an analogy for a solution for dealing with the rebasing issue, and some justification of why I think it's better than using git commit hashes, despite the disadvantages. The docker versioning is my own use-case, with some parallels to the problem you're solving with this project.

---

I rebuild a docker image whenever the contents of the repository change, roughly speaking. The dockerfile, app files, any assets. All of those get put into the docker image, so if any of those change, the docker image needs to be rebuilt. However, when I merge a PR on GitHub, whether by rebasing, merging, or squashing, it will always create new commits.

This is mostly fine, except that, since I know that the files have not changed, there shouldn't be a need to rebuild the image. If I identified the docker image based on the git commit hash, then it would always change. If I instead identify the docker image version with the git tree hash of the root of the repository, then it won't rebuild if the files haven't actually changed, which is the desired behavior.

---

As far as migrations, no, I do _not_ apply migrations directly to production from my branches. Only the master branch applies migrations to production. However, while still part of a pull request that will be either rebased or squashed (my preferred option), I find it critical that migrations be _tested_ on local, development, and staging environments as appropriate. I'm not willing to trust a script to generate a migration file and without checking and making sure that the auto-generation didn't do something crazy. Plus, there are some changes, like data migrations and so forth, that an auto-generation script simply couldn't be expected to be aware of.

Once I have things fully tested, I then want to merge and deploy with those tested and trusted migrations. But if the act of merging is going to make those migrations invalid, it's really difficult to have that fit my uses.

---

The root cause of the challenges is the determination that the version of the migration should match the git commit hash. My feeling is that this is the incorrect choice, though I can certainly understand the motivation. It's really cool that you can specify the hash of the git commit when getting ready to generate new migrations.

Here's an idea that I think makes sense to me. What if there were some configuration to specify the location or locations of the schema file(s), and the program would automatically dereference git commit hashes using that configuration? That way you wouldn't lose that cool feature, but it would allow you to write the versions of the schemas to migrate between as hashes of the actual files in question (using git, or directly sha1sum, or something) so that it wouldn't break with a rebase or squashing merge workflow.

**Comment by abe-winter** [comment]
thanks for the writeup

the reason why rebases are hard is that automig tries to create a diff for every commit between your SHA1...SHA2 range

I'm planning to support an `--opaque` argument to just diff the files at the two points in history (without creating the intermediate history)

So if your history is:
```
A --> B1 --> C1 --> D1
```
and that gets rebased to
```
A --> B2 --> C2 --> D2
```
And you deployed migrations from B1 and C1, running `automig C1...D2` will not be great :skull_and_crossbones: -- it will undo the C1 migration to get back to B2.

But with `--opaque` it would just do a diff between the SQL files in B1 and C2 without trying to reconstruct the history

**Comment by abe-winter** [comment]
it sounds like your use case is:
```
master: A ----------------> S ----------------> T
branch:  \--> F1 --> F2 --/  \--> G1 --> G2 --/
```
And the concern is that a migration to staging from F2 will confuse G1, because F2 isn't in G1's history?

**Comment by ryanhiebert** [comment]
Yeah, I think that's right. I'm going to validate at F2, to make sure that the migrations are correct and working how they need to be. Then when I go to deploy S, because it's been squashed, there won't actually be a valid migration from A -> S, which is what I need, because it's actually got a migration from A -> F2. The solution for this is to be addressing the schemas based on their _content_, rather than based on their _commit_, which is what I'm advocating for. Instead of using the commit hash to identify the state of the database schema, instead run sha1sum or something like it over the contents of the schema file(s), and use that hash as the identifier instead. That would be a consistent identifier even in different commit hashes. It will make some things more difficult, so I don't know if you're going to be willing to go this route, but I think it's the better choice.

If you decide that's unworkable, and you may, given the philosophy you've laid out, then I might be interested in working up my own thought as a separate project. In that case it may be useful to see if we can come up with some common dependency for the really cool additional work to take a schema and produce a good ORM from it.

**Comment by abe-winter** [comment]
in the example above, as long as you run all prod migrations from the master branch, the `A --> S` migration will work

if I'm understanding correctly, the `A --> F2` migration has only been applied in your staging env

**Comment by ryanhiebert** [comment]
I think that I misunderstood how the tool works, I apologize. I thought it generated SQL schema migrations, similar to alembic or Django migrations, but in SQL and based on SQL. That seems to be incorrect. This seems like it should make me nervous, since I cannot proof, commit, and validate on my various instances that I've got the migration doing the right thing. And it means that there really wouldn't be a good way to write and test migrations that _don't_ change the schema, but only ensure that data is consistent.

If all of that sounds like I'm understanding this project correctly now, and I wasn't previously, and if this seems out of scope for the project as you envision it, feel free to close this issue. Thanks for having this discussion with me, I appreciate the time that you've taken.

**Comment by abe-winter** [comment]
??? it does generate sql migrations in sql from sql

there's an [example of the output](https://github.com/abe-winter/automigrate#whats-happening-under-the-covers) in the readme

**Comment by abe-winter** [comment]
oh wait you want to generate traditional migration files with & up and a down and then check them in

yeah this doesn't do that. It relies on git for all its state

feel free to close this if it seems like automig isn't a good fit. LMK if you think the docs can be improved to make clear what this tool does.
